### PR TITLE
Adds Navigator and navigation utilities

### PR DESCRIPTION
**Pull request by johnpatrickmorgan**
This PR:

- Adds a `Navigator` object accessible via the environment, which gives access to the current navigation path.
- Adds utilities for pushing and popping via the navigator, or directly with an Array or NBNavigationPath.

## Usage:
The navigator can be accessed via the environment, e.g. for a NBNavigationPath-backed stack:

`@EnvironmentObject var navigator: PathNavigator`

Or for an Array-backed stack:

`@EnvironmentObject var navigator: Navigator<Screen>`

The navigator can then be used in a variety of ways:

```swift
navigator.push(Profile(name: "John"))

navigator.pop()

navigator.popToRoot()

navigator.popTo(Profile.self)
```

### CODE REVIEW

**Comment by muellnes** [comment]
Thank you very much this looks already very good to me. I did add your suggested solution already to our project and the Navigator class looks very close to it, including also some of the nice utility functions. So when I saw yours, I got very happy that I can in the future remove everything out of our code base and totally rely on your library.

**Comment by ivan-kolesov** [comment]
Hi. If I push a page to stack like this: navigator.push(Screen.generic(PageParameters(title: "page 2")))
how I could return to the page using popTo method?
It's work: navigator.popTo(Screen.generic(PageParameters(title: "page 2"))), but I have to know exact parameters. But I want to back to a recent page of type Screen.generic with any parameters.

**Comment by johnpatrickmorgan** [comment]
@ivan-kolesov You can do something like this:
```swift
navigator.popTo(where: { screen in
  guard case .generic = screen else {
    return false
  }
  return true
})
```

**Comment by ivan-kolesov** [comment]
> @ivan-kolesov You can do something like this:
> 
> ```swift
> navigator.popTo(where: { screen in
>   guard case .generic = screen else {
>     return false
>   }
>   return true
> })
> ```

error complining: Type 'AnyHashable' has no member 'generic'
because NBNavigationPath contains Hashable values

**Comment by johnpatrickmorgan** [comment]
@ivan-kolesov Ah right, you're using `NBNavigationPath`.  In that case, try:
```swift
navigator.popTo(where: { value in
  guard let screen = value as? Screen, case .generic = screen else {
    return false
  }
  return true
})
```

**Comment by ivan-kolesov** [comment]
> @ivan-kolesov Ah right, you're using `NBNavigationPath`. In that case, try:
> 
> ```swift
> navigator.popTo(where: { value in
>   guard let screen = value as? Screen, case .generic = screen else {
>     return false
>   }
>   return true
> })
> ```

Thank you. Thats working. Might be good adding support those construction as extension to navigator to return a recent screen with parameters.

**Pull request merged**
