### PR TITLE
Bugfix: Support class inheritance

### PR DESCRIPTION
**Pull request by ggrell**
Fixes for missing inherited class support for navigation destination types

The way `build<T>(_ typedData: T) → AnyView` was implemented, it didn't support using classes where the `.navigationDestination()` is triggered off a base class and navigation was happening via a child class. This refactoring uses `Mirror(reflecting:)` to get the type info for the given `typedData`, and if no matching navigation destination factory is found, it tries again for its superclass until either a match is found or there are no more superclasses to check.

This also required me to split out the check for `LocalDestinationID` since that doesn't need to be in the loop and only needs to be checked on `typedData` initially.

### CODE REVIEW

**Comment by johnpatrickmorgan** [comment]
Thanks very much for raising this PR @ggrell! I've merged your changes with a [small tweak](https://github.com/johnpatrickmorgan/NavigationBackport/commit/11ae789f774bc8c7d2c67b21f9c827147aa344fa) to avoid explicitly unwrapping the mirror. It's available in v0.7.2. Thanks again!

**Comment by ggrell** [comment]
Thank you for building this library!!! LMK if I can help at all with the `NavigationSplitView` implementation.

**Comment by johnpatrickmorgan** [comment]
Thanks @ggrell ! To be honest, I think the implementation is complete in #28, but I haven't had a chance to test it thoroughly (and document its shortcomings), and I'm scared to merge it yet in case it breaks something subtle! :laughing

**Comment by ggrell** [comment]
> Thanks @ggrell ! To be honest, I think the implementation is complete in #28, but I haven't had a chance to test it thoroughly (and document its shortcomings), and I'm scared to merge it yet in case it breaks something subtle! 😆

I have an app architecture test app that's iOS 16+ now, I'll see if it works OK with NBP.

**Pull request merged**
